chmod +x base_checar.sh
chmod +x checar.sh
chmod +x ejecutar_gamit_1.sh
chmod +x ejecutar_gamit_2.sh
chmod +x ejecutar_gamit_3.sh
chmod +x ejecutar_gamit_4.sh
chmod +x ejecutar_gamit_5.sh
chmod +x ejecutar_gamit_6.sh
chmod +x ejecutar_gamit_7.sh
chmod +x ejecutar_gamit_8.sh
chmod +x ejecutar_gamit_9.sh
chmod +x ejecutar_gamit_10.sh
chmod +x ejecutar_gamit_11.sh
chmod +x ejecutar_gamit_12.sh
chmod +x ejecutar_gamit_F.sh
chmod +x finalizar.sh
chmod +x iniciar.sh
chmod +x limpiar.sh
chmod +x repetir.sh