./ejecutar_gamit_1.sh
./ejecutar_gamit_2.sh
./ejecutar_gamit_3.sh
./ejecutar_gamit_4.sh
./ejecutar_gamit_5.sh
./ejecutar_gamit_6.sh
./ejecutar_gamit_7.sh
./ejecutar_gamit_8.sh
./ejecutar_gamit_9.sh
./ejecutar_gamit_10.sh
./ejecutar_gamit_11.sh
./ejecutar_gamit_12.sh