sh_gamit -expt exme -d 2015 001 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_001.txt
sh_gamit -expt exme -d 2015 002 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_002.txt
sh_gamit -expt exme -d 2015 003 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_003.txt
sh_gamit -expt exme -d 2015 004 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_004.txt
sh_gamit -expt exme -d 2015 005 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_005.txt
sh_gamit -expt exme -d 2015 006 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_006.txt
sh_gamit -expt exme -d 2015 007 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_007.txt
sh_gamit -expt exme -d 2015 008 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_008.txt
sh_gamit -expt exme -d 2015 009 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_009.txt
sh_gamit -expt exme -d 2015 010 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_010.txt
sh_gamit -expt exme -d 2015 011 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_011.txt
sh_gamit -expt exme -d 2015 012 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_012.txt
sh_gamit -expt exme -d 2015 013 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_013.txt
sh_gamit -expt exme -d 2015 014 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_014.txt
sh_gamit -expt exme -d 2015 015 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_015.txt
sh_gamit -expt exme -d 2015 016 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_016.txt
sh_gamit -expt exme -d 2015 017 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_017.txt
sh_gamit -expt exme -d 2015 018 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_018.txt
sh_gamit -expt exme -d 2015 019 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_019.txt
sh_gamit -expt exme -d 2015 020 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_020.txt
sh_gamit -expt exme -d 2015 021 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_021.txt
sh_gamit -expt exme -d 2015 022 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_022.txt
sh_gamit -expt exme -d 2015 023 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_023.txt
sh_gamit -expt exme -d 2015 024 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_024.txt
sh_gamit -expt exme -d 2015 025 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_025.txt
sh_gamit -expt exme -d 2015 026 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_026.txt
sh_gamit -expt exme -d 2015 027 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_027.txt
sh_gamit -expt exme -d 2015 028 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_028.txt
sh_gamit -expt exme -d 2015 029 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_029.txt
sh_gamit -expt exme -d 2015 030 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_030.txt
sh_gamit -expt exme -d 2015 031 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_031.txt
sh_gamit -expt exme -d 2015 032 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_032.txt
sh_gamit -expt exme -d 2015 033 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_033.txt
sh_gamit -expt exme -d 2015 034 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_034.txt
sh_gamit -expt exme -d 2015 035 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_035.txt
sh_gamit -expt exme -d 2015 036 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_036.txt
sh_gamit -expt exme -d 2015 037 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_037.txt
sh_gamit -expt exme -d 2015 038 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_038.txt
sh_gamit -expt exme -d 2015 039 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_039.txt
sh_gamit -expt exme -d 2015 040 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_040.txt
sh_gamit -expt exme -d 2015 041 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_041.txt
sh_gamit -expt exme -d 2015 042 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_042.txt
sh_gamit -expt exme -d 2015 043 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_043.txt
sh_gamit -expt exme -d 2015 044 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_044.txt
sh_gamit -expt exme -d 2015 045 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_045.txt
sh_gamit -expt exme -d 2015 046 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_046.txt
sh_gamit -expt exme -d 2015 047 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_047.txt
sh_gamit -expt exme -d 2015 048 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_048.txt
sh_gamit -expt exme -d 2015 049 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_049.txt
sh_gamit -expt exme -d 2015 050 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_050.txt
sh_gamit -expt exme -d 2015 051 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_051.txt
sh_gamit -expt exme -d 2015 052 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_052.txt
sh_gamit -expt exme -d 2015 053 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_053.txt
sh_gamit -expt exme -d 2015 054 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_054.txt
sh_gamit -expt exme -d 2015 055 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_055.txt
sh_gamit -expt exme -d 2015 056 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_056.txt
sh_gamit -expt exme -d 2015 057 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_057.txt
sh_gamit -expt exme -d 2015 058 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_058.txt
sh_gamit -expt exme -d 2015 059 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_059.txt
sh_gamit -expt exme -d 2015 060 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_060.txt
sh_gamit -expt exme -d 2015 061 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_061.txt
sh_gamit -expt exme -d 2015 062 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_062.txt
sh_gamit -expt exme -d 2015 063 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_063.txt
sh_gamit -expt exme -d 2015 064 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_064.txt
sh_gamit -expt exme -d 2015 065 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_065.txt
sh_gamit -expt exme -d 2015 066 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_066.txt
sh_gamit -expt exme -d 2015 067 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_067.txt
sh_gamit -expt exme -d 2015 068 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_068.txt
sh_gamit -expt exme -d 2015 069 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_069.txt
sh_gamit -expt exme -d 2015 070 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_070.txt
sh_gamit -expt exme -d 2015 071 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_071.txt
sh_gamit -expt exme -d 2015 072 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_072.txt
sh_gamit -expt exme -d 2015 073 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_073.txt
sh_gamit -expt exme -d 2015 074 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_074.txt
sh_gamit -expt exme -d 2015 075 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_075.txt
sh_gamit -expt exme -d 2015 076 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_076.txt
sh_gamit -expt exme -d 2015 077 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_077.txt
sh_gamit -expt exme -d 2015 078 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_078.txt
sh_gamit -expt exme -d 2015 079 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_079.txt
sh_gamit -expt exme -d 2015 080 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_080.txt
sh_gamit -expt exme -d 2015 081 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_081.txt
sh_gamit -expt exme -d 2015 082 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_082.txt
sh_gamit -expt exme -d 2015 083 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_083.txt
sh_gamit -expt exme -d 2015 084 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_084.txt
sh_gamit -expt exme -d 2015 085 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_085.txt
sh_gamit -expt exme -d 2015 086 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_086.txt
sh_gamit -expt exme -d 2015 087 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_087.txt
sh_gamit -expt exme -d 2015 088 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_088.txt
sh_gamit -expt exme -d 2015 089 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_089.txt
sh_gamit -expt exme -d 2015 090 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_090.txt
sh_gamit -expt exme -d 2015 091 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_091.txt
sh_gamit -expt exme -d 2015 092 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_092.txt
sh_gamit -expt exme -d 2015 093 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_093.txt
sh_gamit -expt exme -d 2015 094 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_094.txt
sh_gamit -expt exme -d 2015 095 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_095.txt
sh_gamit -expt exme -d 2015 096 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_096.txt
sh_gamit -expt exme -d 2015 097 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_097.txt
sh_gamit -expt exme -d 2015 098 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_098.txt
sh_gamit -expt exme -d 2015 099 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_099.txt
sh_gamit -expt exme -d 2015 100 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_100.txt
sh_gamit -expt exme -d 2015 101 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_101.txt
sh_gamit -expt exme -d 2015 102 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_102.txt
sh_gamit -expt exme -d 2015 103 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_103.txt
sh_gamit -expt exme -d 2015 104 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_104.txt
sh_gamit -expt exme -d 2015 105 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_105.txt
sh_gamit -expt exme -d 2015 106 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_106.txt
sh_gamit -expt exme -d 2015 107 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_107.txt
sh_gamit -expt exme -d 2015 108 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_108.txt
sh_gamit -expt exme -d 2015 109 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_109.txt
sh_gamit -expt exme -d 2015 110 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_110.txt
sh_gamit -expt exme -d 2015 111 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_111.txt
sh_gamit -expt exme -d 2015 112 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_112.txt
sh_gamit -expt exme -d 2015 113 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_113.txt
sh_gamit -expt exme -d 2015 114 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_114.txt
sh_gamit -expt exme -d 2015 115 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_115.txt
sh_gamit -expt exme -d 2015 116 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_116.txt
sh_gamit -expt exme -d 2015 117 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_117.txt
sh_gamit -expt exme -d 2015 118 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_118.txt
sh_gamit -expt exme -d 2015 119 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_119.txt
sh_gamit -expt exme -d 2015 120 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_120.txt
sh_gamit -expt exme -d 2015 121 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_121.txt
sh_gamit -expt exme -d 2015 122 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_122.txt
sh_gamit -expt exme -d 2015 123 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_123.txt
sh_gamit -expt exme -d 2015 124 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_124.txt
sh_gamit -expt exme -d 2015 125 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_125.txt
sh_gamit -expt exme -d 2015 126 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_126.txt
sh_gamit -expt exme -d 2015 127 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_127.txt
sh_gamit -expt exme -d 2015 128 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_128.txt
sh_gamit -expt exme -d 2015 129 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_129.txt
sh_gamit -expt exme -d 2015 130 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_130.txt
sh_gamit -expt exme -d 2015 131 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_131.txt
sh_gamit -expt exme -d 2015 132 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_132.txt
sh_gamit -expt exme -d 2015 133 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_133.txt
sh_gamit -expt exme -d 2015 134 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_134.txt
sh_gamit -expt exme -d 2015 135 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_135.txt
sh_gamit -expt exme -d 2015 136 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_136.txt
sh_gamit -expt exme -d 2015 137 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_137.txt
sh_gamit -expt exme -d 2015 138 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_138.txt
sh_gamit -expt exme -d 2015 139 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_139.txt
sh_gamit -expt exme -d 2015 140 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_140.txt
sh_gamit -expt exme -d 2015 141 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_141.txt
sh_gamit -expt exme -d 2015 142 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_142.txt
sh_gamit -expt exme -d 2015 143 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_143.txt
sh_gamit -expt exme -d 2015 144 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_144.txt
sh_gamit -expt exme -d 2015 145 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_145.txt
sh_gamit -expt exme -d 2015 146 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_146.txt
sh_gamit -expt exme -d 2015 147 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_147.txt
sh_gamit -expt exme -d 2015 148 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_148.txt
sh_gamit -expt exme -d 2015 149 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_149.txt
sh_gamit -expt exme -d 2015 150 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_150.txt
sh_gamit -expt exme -d 2015 151 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_151.txt
sh_gamit -expt exme -d 2015 152 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_152.txt
sh_gamit -expt exme -d 2015 153 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_153.txt
sh_gamit -expt exme -d 2015 154 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_154.txt
sh_gamit -expt exme -d 2015 155 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_155.txt
sh_gamit -expt exme -d 2015 156 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_156.txt
sh_gamit -expt exme -d 2015 157 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_157.txt
sh_gamit -expt exme -d 2015 158 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_158.txt
sh_gamit -expt exme -d 2015 159 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_159.txt
sh_gamit -expt exme -d 2015 160 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_160.txt
sh_gamit -expt exme -d 2015 161 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_161.txt
sh_gamit -expt exme -d 2015 162 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_162.txt
sh_gamit -expt exme -d 2015 163 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_163.txt
sh_gamit -expt exme -d 2015 164 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_164.txt
sh_gamit -expt exme -d 2015 165 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_165.txt
sh_gamit -expt exme -d 2015 166 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_166.txt
sh_gamit -expt exme -d 2015 167 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_167.txt
sh_gamit -expt exme -d 2015 168 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_168.txt
sh_gamit -expt exme -d 2015 169 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_169.txt
sh_gamit -expt exme -d 2015 170 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_170.txt
sh_gamit -expt exme -d 2015 171 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_171.txt
sh_gamit -expt exme -d 2015 172 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_172.txt
sh_gamit -expt exme -d 2015 173 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_173.txt
sh_gamit -expt exme -d 2015 174 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_174.txt
sh_gamit -expt exme -d 2015 175 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_175.txt
sh_gamit -expt exme -d 2015 176 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_176.txt
sh_gamit -expt exme -d 2015 177 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_177.txt
sh_gamit -expt exme -d 2015 178 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_178.txt
sh_gamit -expt exme -d 2015 179 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_179.txt
sh_gamit -expt exme -d 2015 180 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_180.txt
sh_gamit -expt exme -d 2015 181 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_181.txt
sh_gamit -expt exme -d 2015 182 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_182.txt
sh_gamit -expt exme -d 2015 183 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_183.txt
sh_gamit -expt exme -d 2015 184 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_184.txt
sh_gamit -expt exme -d 2015 185 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_185.txt
sh_gamit -expt exme -d 2015 186 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_186.txt
sh_gamit -expt exme -d 2015 187 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_187.txt
sh_gamit -expt exme -d 2015 188 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_188.txt
sh_gamit -expt exme -d 2015 189 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_189.txt
sh_gamit -expt exme -d 2015 190 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_190.txt
sh_gamit -expt exme -d 2015 191 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_191.txt
sh_gamit -expt exme -d 2015 192 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_192.txt
sh_gamit -expt exme -d 2015 193 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_193.txt
sh_gamit -expt exme -d 2015 194 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_194.txt
sh_gamit -expt exme -d 2015 195 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_195.txt
sh_gamit -expt exme -d 2015 196 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_196.txt
sh_gamit -expt exme -d 2015 197 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_197.txt
sh_gamit -expt exme -d 2015 198 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_198.txt
sh_gamit -expt exme -d 2015 199 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_199.txt
sh_gamit -expt exme -d 2015 200 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_200.txt
sh_gamit -expt exme -d 2015 201 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_201.txt
sh_gamit -expt exme -d 2015 202 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_202.txt
sh_gamit -expt exme -d 2015 203 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_203.txt
sh_gamit -expt exme -d 2015 204 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_204.txt
sh_gamit -expt exme -d 2015 205 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_205.txt
sh_gamit -expt exme -d 2015 206 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_206.txt
sh_gamit -expt exme -d 2015 207 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_207.txt
sh_gamit -expt exme -d 2015 208 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_208.txt
sh_gamit -expt exme -d 2015 209 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_209.txt
sh_gamit -expt exme -d 2015 210 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_210.txt
sh_gamit -expt exme -d 2015 211 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_211.txt
sh_gamit -expt exme -d 2015 212 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_212.txt
sh_gamit -expt exme -d 2015 213 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_213.txt
sh_gamit -expt exme -d 2015 214 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_214.txt
sh_gamit -expt exme -d 2015 215 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_215.txt
sh_gamit -expt exme -d 2015 216 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_216.txt
sh_gamit -expt exme -d 2015 217 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_217.txt
sh_gamit -expt exme -d 2015 218 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_218.txt
sh_gamit -expt exme -d 2015 219 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_219.txt
sh_gamit -expt exme -d 2015 220 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_220.txt
sh_gamit -expt exme -d 2015 221 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_221.txt
sh_gamit -expt exme -d 2015 222 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_222.txt
sh_gamit -expt exme -d 2015 223 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_223.txt
sh_gamit -expt exme -d 2015 224 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_224.txt
sh_gamit -expt exme -d 2015 225 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_225.txt
sh_gamit -expt exme -d 2015 226 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_226.txt
sh_gamit -expt exme -d 2015 227 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_227.txt
sh_gamit -expt exme -d 2015 228 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_228.txt
sh_gamit -expt exme -d 2015 229 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_229.txt
sh_gamit -expt exme -d 2015 230 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_230.txt
sh_gamit -expt exme -d 2015 231 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_231.txt
sh_gamit -expt exme -d 2015 232 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_232.txt
sh_gamit -expt exme -d 2015 233 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_233.txt
sh_gamit -expt exme -d 2015 234 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_234.txt
sh_gamit -expt exme -d 2015 235 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_235.txt
sh_gamit -expt exme -d 2015 236 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_236.txt
sh_gamit -expt exme -d 2015 237 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_237.txt
sh_gamit -expt exme -d 2015 238 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_238.txt
sh_gamit -expt exme -d 2015 239 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_239.txt
sh_gamit -expt exme -d 2015 240 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_240.txt
sh_gamit -expt exme -d 2015 241 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_241.txt
sh_gamit -expt exme -d 2015 242 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_242.txt
sh_gamit -expt exme -d 2015 243 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_243.txt
sh_gamit -expt exme -d 2015 244 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_244.txt
sh_gamit -expt exme -d 2015 245 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_245.txt
sh_gamit -expt exme -d 2015 246 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_246.txt
sh_gamit -expt exme -d 2015 247 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_247.txt
sh_gamit -expt exme -d 2015 248 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_248.txt
sh_gamit -expt exme -d 2015 249 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_249.txt
sh_gamit -expt exme -d 2015 250 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_250.txt
sh_gamit -expt exme -d 2015 251 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_251.txt
sh_gamit -expt exme -d 2015 252 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_252.txt
sh_gamit -expt exme -d 2015 253 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_253.txt
sh_gamit -expt exme -d 2015 254 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_254.txt
sh_gamit -expt exme -d 2015 255 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_255.txt
sh_gamit -expt exme -d 2015 256 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_256.txt
sh_gamit -expt exme -d 2015 257 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_257.txt
sh_gamit -expt exme -d 2015 258 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_258.txt
sh_gamit -expt exme -d 2015 259 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_259.txt
sh_gamit -expt exme -d 2015 260 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_260.txt
sh_gamit -expt exme -d 2015 261 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_261.txt
sh_gamit -expt exme -d 2015 262 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_262.txt
sh_gamit -expt exme -d 2015 263 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_263.txt
sh_gamit -expt exme -d 2015 264 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_264.txt
sh_gamit -expt exme -d 2015 265 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_265.txt
sh_gamit -expt exme -d 2015 266 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_266.txt
sh_gamit -expt exme -d 2015 267 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_267.txt
sh_gamit -expt exme -d 2015 268 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_268.txt
sh_gamit -expt exme -d 2015 269 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_269.txt
sh_gamit -expt exme -d 2015 270 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_270.txt
sh_gamit -expt exme -d 2015 271 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_271.txt
sh_gamit -expt exme -d 2015 272 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_272.txt
sh_gamit -expt exme -d 2015 273 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_273.txt
sh_gamit -expt exme -d 2015 274 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_274.txt
sh_gamit -expt exme -d 2015 275 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_275.txt
sh_gamit -expt exme -d 2015 276 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_276.txt
sh_gamit -expt exme -d 2015 277 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_277.txt
sh_gamit -expt exme -d 2015 278 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_278.txt
sh_gamit -expt exme -d 2015 279 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_279.txt
sh_gamit -expt exme -d 2015 280 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_280.txt
sh_gamit -expt exme -d 2015 281 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_281.txt
sh_gamit -expt exme -d 2015 282 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_282.txt
sh_gamit -expt exme -d 2015 283 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_283.txt
sh_gamit -expt exme -d 2015 284 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_284.txt
sh_gamit -expt exme -d 2015 285 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_285.txt
sh_gamit -expt exme -d 2015 286 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_286.txt
sh_gamit -expt exme -d 2015 287 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_287.txt
sh_gamit -expt exme -d 2015 288 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_288.txt
sh_gamit -expt exme -d 2015 289 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_289.txt
sh_gamit -expt exme -d 2015 290 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_290.txt
sh_gamit -expt exme -d 2015 291 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_291.txt
sh_gamit -expt exme -d 2015 292 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_292.txt
sh_gamit -expt exme -d 2015 293 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_293.txt
sh_gamit -expt exme -d 2015 294 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_294.txt
sh_gamit -expt exme -d 2015 295 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_295.txt
sh_gamit -expt exme -d 2015 296 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_296.txt
sh_gamit -expt exme -d 2015 297 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_297.txt
sh_gamit -expt exme -d 2015 298 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_298.txt
sh_gamit -expt exme -d 2015 299 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_299.txt
sh_gamit -expt exme -d 2015 300 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_300.txt
sh_gamit -expt exme -d 2015 301 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_301.txt
sh_gamit -expt exme -d 2015 302 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_302.txt
sh_gamit -expt exme -d 2015 303 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_303.txt
sh_gamit -expt exme -d 2015 304 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_304.txt
sh_gamit -expt exme -d 2015 305 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_305.txt
sh_gamit -expt exme -d 2015 306 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_306.txt
sh_gamit -expt exme -d 2015 307 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_307.txt
sh_gamit -expt exme -d 2015 308 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_308.txt
sh_gamit -expt exme -d 2015 309 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_309.txt
sh_gamit -expt exme -d 2015 310 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_310.txt
sh_gamit -expt exme -d 2015 311 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_311.txt
sh_gamit -expt exme -d 2015 312 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_312.txt
sh_gamit -expt exme -d 2015 313 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_313.txt
sh_gamit -expt exme -d 2015 314 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_314.txt
sh_gamit -expt exme -d 2015 315 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_315.txt
sh_gamit -expt exme -d 2015 316 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_316.txt
sh_gamit -expt exme -d 2015 317 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_317.txt
sh_gamit -expt exme -d 2015 318 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_318.txt
sh_gamit -expt exme -d 2015 319 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_319.txt
sh_gamit -expt exme -d 2015 320 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_320.txt
sh_gamit -expt exme -d 2015 321 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_321.txt
sh_gamit -expt exme -d 2015 322 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_322.txt
sh_gamit -expt exme -d 2015 323 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_323.txt
sh_gamit -expt exme -d 2015 324 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_324.txt
sh_gamit -expt exme -d 2015 325 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_325.txt
sh_gamit -expt exme -d 2015 326 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_326.txt
sh_gamit -expt exme -d 2015 327 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_327.txt
sh_gamit -expt exme -d 2015 328 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_328.txt
sh_gamit -expt exme -d 2015 329 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_329.txt
sh_gamit -expt exme -d 2015 330 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_330.txt
sh_gamit -expt exme -d 2015 331 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_331.txt
sh_gamit -expt exme -d 2015 332 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_332.txt
sh_gamit -expt exme -d 2015 333 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_333.txt
sh_gamit -expt exme -d 2015 334 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_334.txt
sh_gamit -expt exme -d 2015 335 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_335.txt
sh_gamit -expt exme -d 2015 336 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_336.txt
sh_gamit -expt exme -d 2015 337 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_337.txt
sh_gamit -expt exme -d 2015 338 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_338.txt
sh_gamit -expt exme -d 2015 339 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_339.txt
sh_gamit -expt exme -d 2015 340 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_340.txt
sh_gamit -expt exme -d 2015 341 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_341.txt
sh_gamit -expt exme -d 2015 342 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_342.txt
sh_gamit -expt exme -d 2015 343 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_343.txt
sh_gamit -expt exme -d 2015 344 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_344.txt
sh_gamit -expt exme -d 2015 345 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_345.txt
sh_gamit -expt exme -d 2015 346 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_346.txt
sh_gamit -expt exme -d 2015 347 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_347.txt
sh_gamit -expt exme -d 2015 348 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_348.txt
sh_gamit -expt exme -d 2015 349 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_349.txt
sh_gamit -expt exme -d 2015 350 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_350.txt
sh_gamit -expt exme -d 2015 351 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_351.txt
sh_gamit -expt exme -d 2015 352 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_352.txt
sh_gamit -expt exme -d 2015 353 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_353.txt
sh_gamit -expt exme -d 2015 354 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_354.txt
sh_gamit -expt exme -d 2015 355 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_355.txt
sh_gamit -expt exme -d 2015 356 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_356.txt
sh_gamit -expt exme -d 2015 357 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_357.txt
sh_gamit -expt exme -d 2015 358 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_358.txt
sh_gamit -expt exme -d 2015 359 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_359.txt
sh_gamit -expt exme -d 2015 360 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_360.txt
sh_gamit -expt exme -d 2015 361 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_361.txt
sh_gamit -expt exme -d 2015 362 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_362.txt
sh_gamit -expt exme -d 2015 363 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_363.txt
sh_gamit -expt exme -d 2015 364 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_364.txt
sh_gamit -expt exme -d 2015 365 -pres ELEV -orbit IGSF -copt x k p -dopts c ao > errores/archivo_error_365.txt
