from os import listdir
import os
import sys
anos=[]
cuenta=[]

carpeta=sys.argv[1]
ano1=int(sys.argv[2])
ano2=int(sys.argv[3])+1

archivo = open (carpeta+"/lista_datos.txt","w")

ref_sites = "ABMF ABPO ADE1 AIRA ALBH ALGO ALIC ALRT AMC2 ANKR AOML AREQ AREV ARTU ASC1 ASPA AUCK BADG BAHR BAKE BAN2 BARH BHR1 BHR2 BILI BJCO BJFS BOGT BOR1 BRAZ BREW BRFT BRMU BRST BRUS BUCU BUE2 CAGL CAGZ CAS1 CCJM CEDU CFAG CHAT CHPI CHTI CHUM CHUR CIC1 CKIS CNMR COCO COYQ CRAO CRO1 DAEJ DARW DAV1 DGAR DGAV DRAG DRAO DUBO DUBR DUM1 EISL EPRT FAA1 FAIR FALK FLIN FORT FUNC GALA GLPS GLSV GMAS GMSD GODE GODZ GOL2 GOLD GOUG GRAS GRAZ GUAM GUAO GUAT GUUG HARB HERS HERT HLFX HNLC HOB2 HOFN HOLB HOLM HRAO HYDE IISC INVK IRKJ IRKM IRKT ISPA ISTA JAB1 JOZ2 JOZE JPLM KARR KAT1 KELY KERG KGNI KHAJ KIRI KIRU KIT3 KOKB KOKV KOSG KOUC KOUR KUNM KWJ1 LAE1 LAUT LHAS LHAZ LMMF LPAL LPGS LROC MAC1 MAL2 MALD MALI MANA MAS1 MAT1 MATE MAUI MAW1 MBAR MCIL MCM4 MDO1 MDVJ MDVO MEDI METS METZ MKEA MOBS MONP MORP MQZG MTKA NAIN NAMA NANO NAUR NICO NIUM NKLG NLIB NNOR NOT1 NOUM NRC1 NRIL NRMD NURK NVSK NYA1 NYAL OHI2 OHI3 OHIG ONSA OSN1 OUS2 PALM PARC PDEL PERT PETP PIE1 PIMO POHN POL2 POLV POTS PRDS PRE1 QAQ1 QIKI QUI2 QUIN RABT RAMO RBAY RCMN RECF RESO REUN RIGA RIO2 RIOG SALU SANT SAVO SCH2 SCOR SCUB SELE SFER SHAO SIMO SOFI SSIA STHL STJO SUTH SUTM SUWN SYDN SYOG TAEJ TAH1 TASH TCMS TEHN THTI THU1 THU3 TID1 TIDB TIXI TLSE TNML TOW2 TRAB TRO1 TROM TSKB TUVA TWTF UFPR ULAB UNBJ UNSA URUM USN3 USNO UZHL VACS VESL VILL VNDP WES2 WHIT WILL WIND WSRT WTZR WUHN XMIS YAKT YAR1 YAR2 YARR YEBE YELL YIBL ZAMB ZECK ZIMJ ZIMM"
estaciones1 = ref_sites.split(" ")

archivo.write("EST,")
for i in range(ano1,ano2,1):
	anos.append(str(i))
	cuenta.append(0)
	archivo.write(str(i)+",")

archivo.write("TOTAL"+"\n")

for estacion in estaciones1:
	archivo.write(str(estacion[0:4])+",")
	tempo= open (carpeta+"/series/"+estacion+".series","r")
	roto=0
	cuentanos=0
	for ti in tempo:
		ano_act=ti[0:4]
		for xi in range(len(anos)):
			ano_temp=anos[xi]
			if ano_temp == ano_act:
				cuenta[xi]=cuenta[xi]+1
	for xi in range(len(anos)):	
		archivo.write(str(cuenta[xi])+",")
		cuentanos=cuentanos+cuenta[xi]
		cuenta[xi]=0
	archivo.write(str(cuentanos)+"\n")
	tempo.close()
archivo.close()